//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class dbSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static dbSettings defaultInstance = ((dbSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new dbSettings())));
        
        public static dbSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://127.0.0.1/Supermarket")]
        public string MONGOLAB_URI {
            get {
                return ((string)(this["MONGOLAB_URI"]));
            }
            set {
                this["MONGOLAB_URI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Database=supermarket;Uid=root;Pwd=;")]
        public string MySqlConnectionString {
            get {
                return ((string)(this["MySqlConnectionString"]));
            }
            set {
                this["MySqlConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=D:\\Projects\\VisualStudio2012\\Telerik\\Supermarket\\CSharpDevelopment\\Da" +
            "taBase\\ADONET\\ADONET\\ADONET.WebApp\\books.db;Version=3;")]
        public string SQLiteConnectionString {
            get {
                return ((string)(this["SQLiteConnectionString"]));
            }
            set {
                this["SQLiteConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=.; Database=SupermarketDatabase; Integrated Security=true")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
            set {
                this["SqlConnectionString"] = value;
            }
        }
    }
}
