//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int Id { get; set; }
        public int VendorId { get; set; }
        public string Product_Name { get; set; }
        public int MeasureId { get; set; }
        public double Base_Prise { get; set; }
    
        public virtual Measures Measures { get; set; }
        public virtual Vendors Vendors { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
