//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendors
    {
        public Vendors()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public string Vendor_Name { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
