//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Markets
    {
        public Markets()
        {
            this.sales = new HashSet<sales>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<sales> sales { get; set; }
    }
}
