//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetEqualStringCount.ClientTest.GetEqualStringsCountServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetEqualStringsCountServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEqualStringsCount", ReplyAction="http://tempuri.org/IService/GetEqualStringsCountResponse")]
        int GetEqualStringsCount(string firstString, string secoundString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEqualStringsCount", ReplyAction="http://tempuri.org/IService/GetEqualStringsCountResponse")]
        System.Threading.Tasks.Task<int> GetEqualStringsCountAsync(string firstString, string secoundString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : GetEqualStringCount.ClientTest.GetEqualStringsCountServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<GetEqualStringCount.ClientTest.GetEqualStringsCountServiceReference.IService>, GetEqualStringCount.ClientTest.GetEqualStringsCountServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetEqualStringsCount(string firstString, string secoundString) {
            return base.Channel.GetEqualStringsCount(firstString, secoundString);
        }
        
        public System.Threading.Tasks.Task<int> GetEqualStringsCountAsync(string firstString, string secoundString) {
            return base.Channel.GetEqualStringsCountAsync(firstString, secoundString);
        }
    }
}
