//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int Qantity { get; set; }
        public double UnitPrice { get; set; }
        public double Sum { get; set; }
        public int MarketId { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Markets Markets { get; set; }
        public virtual Products Products { get; set; }
    }
}
